semantic_release:
  stage: release
  tags:
    - dev
  image: node:20
  variables:
    GIT_AUTHOR_NAME: 'some-where Bot'
    GIT_AUTHOR_EMAIL: 'noreply@whatever.com'
    GITLAB_TOKEN: $GITLAB_TOKEN
  before_script:
    - git fetch --tags --force
    - git tag -d $(git tag -l) || true
    - |
      COMMIT_MSG="$(git log -1 --pretty=%s)"
      echo "📩 Last commit message: $COMMIT_MSG"
      if echo "$COMMIT_MSG" | grep -qE '^chore\(release\):'; then
        echo "🚫 Detected semantic-release auto commit. Skipping job..."
        exit 0
      fi
  script:
    - npm install
    - npx semantic-release
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_TAG'
      when: never
    - if: '$DEPLOY_MANUAL'
      when: never
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "staging"'
      when: always
    - when: never
